export const copy = {
  ru: {
    localeName: "Русский",
    skip: "Перейти к содержанию",
    navCases: "Дела",
    navHow: "Как это работает",
    report: "Сообщить о проблеме",
    eyebrow: "Прага · общественный контроль",
    heroA: "ВАШ РАЙОН",
    heroB: "НЕ БРОШЕН.",
    intro: "Одно доказанное дело, все ответственные службы и независимая проверка результата.",
    proofLabel: "Публичное доказательство",
    proofTitle: "Закрытая заявка не означает чистую улицу",
    proofBody: "Служба закрыла свой тикет. Жители всё ещё видят проблему. Nahlas показывает обе правды отдельно.",
    casesTitle: "Открытые дела",
    casesIntro: "Сначала проверьте, существует ли уже такое дело. Подтверждение усиливает одно дело и не создаёт новый поток жалоб.",
    caseLabel: "Дело",
    witnesses: "подтверждений",
    days: "дней в наблюдении",
    authority: "Статус службы",
    observed: "Что видно на улице",
    timeline: "Цепочка доказательств",
    corroborate: "Это та же проблема",
    corroborated: "Подтверждение добавлено",
    receipt: "Квитанция маршрута",
    destination: "Получатель",
    channel: "Канал",
    sentAt: "Отправлено",
    externalRef: "Внешний номер",
    payloadHash: "Отпечаток сообщения",
    simulator: "Демонстрация. Ничего не отправляется службам.",
    hotspot: "Повторяющееся место",
    hotspotBody: "Отдельные инциденты остаются отдельными делами. Досье показывает повторяемость и историю вмешательств.",
    howTitle: "Не ящик для жалоб. Контур результата.",
    step1: "Найдите или создайте одно дело",
    step2: "Получите маршрут и квитанцию",
    step3: "Проверьте улицу после ответа",
    reportTitle: "Сначала найдём совпадение",
    reportBody: "Выберите тип, район и публичное место. Форма ищет совпадение и не отправляет данные наружу.",
    category: "Тип проблемы",
    district: "Район",
    locationField: "Публичное место",
    findMatch: "Найти похожие дела",
    close: "Закрыть",
    demoLabel: "Демо в браузере",
    unresolvedStamp: "Всё ещё<br />видно",
    truthNote: "Закрытие службы не меняет наблюдение на улице.",
    memberCases: "отдельных<br />дела",
    matchFound: "Совпадение уже есть",
    matchAction: "Подтвердить это дело",
    noMatch: "Похожих публичных дел не найдено.",
    noDeadline: "Срок не заявлен: обычное сообщение не запускает универсальный юридический таймер.",
    status: {
      sent: "Отправлено",
      accepted: "Принято службой",
      closed: "Закрыто службой",
      unresolved: "Проблема всё ещё видна",
      needs_recheck: "Нужна повторная проверка",
      fixed: "Исправлено и подтверждено"
    }
  },
  cs: {
    localeName: "Čeština",
    skip: "Přejít k obsahu",
    navCases: "Případy",
    navHow: "Jak to funguje",
    report: "Nahlásit problém",
    eyebrow: "Praha · veřejná kontrola",
    heroA: "VAŠE ČTVRŤ",
    heroB: "NENÍ OPUŠTĚNÁ.",
    intro: "Jeden doložený případ, všechny odpovědné služby a nezávislá kontrola výsledku.",
    proofLabel: "Veřejný důkaz",
    proofTitle: "Uzavřený podnět neznamená čistou ulici",
    proofBody: "Úřad uzavřel svůj tiket. Lidé problém stále vidí. Nahlas ukazuje obě pravdy odděleně.",
    casesTitle: "Otevřené případy",
    casesIntro: "Nejdřív ověřte, zda stejný případ už existuje. Potvrzení posílí jeden případ a nevytvoří další podání.",
    caseLabel: "Případ",
    witnesses: "potvrzení",
    days: "dnů sledování",
    authority: "Stav úřadu",
    observed: "Stav na místě",
    timeline: "Řetězec důkazů",
    corroborate: "Je to stejný problém",
    corroborated: "Potvrzení přidáno",
    receipt: "Doklad o směrování",
    destination: "Příjemce",
    channel: "Kanál",
    sentAt: "Odesláno",
    externalRef: "Externí číslo",
    payloadHash: "Otisk zprávy",
    simulator: "Ukázka. Úřadům se nic neodesílá.",
    hotspot: "Opakující se místo",
    hotspotBody: "Jednotlivé události zůstávají samostatnými případy. Spis ukazuje opakování a zásahy.",
    howTitle: "Ne schránka stížností. Smyčka výsledku.",
    step1: "Najděte nebo založte jeden případ",
    step2: "Získejte trasu a doklad",
    step3: "Po odpovědi zkontrolujte místo",
    reportTitle: "Nejdřív najdeme shodu",
    reportBody: "Vyberte typ, městskou část a veřejné místo. Formulář hledá shodu a nic neodesílá ven.",
    category: "Typ problému",
    district: "Městská část",
    locationField: "Veřejné místo",
    findMatch: "Najít podobné případy",
    close: "Zavřít",
    demoLabel: "Ukázka v prohlížeči",
    unresolvedStamp: "Stále<br />viditelné",
    truthNote: "Uzavření úřadem nemění pozorování na ulici.",
    memberCases: "samostatných<br />případů",
    matchFound: "Shoda už existuje",
    matchAction: "Potvrdit tento případ",
    noMatch: "Podobné veřejné případy nebyly nalezeny.",
    noDeadline: "Lhůta není uvedena: běžný podnět nespouští univerzální zákonnou lhůtu.",
    status: {
      sent: "Odesláno",
      accepted: "Přijato úřadem",
      closed: "Uzavřeno úřadem",
      unresolved: "Problém je stále vidět",
      needs_recheck: "Je nutná kontrola",
      fixed: "Opraveno a ověřeno"
    }
  },
  en: {
    localeName: "English",
    skip: "Skip to content",
    navCases: "Cases",
    navHow: "How it works",
    report: "Report a problem",
    eyebrow: "Prague · public accountability",
    heroA: "YOUR DISTRICT",
    heroB: "IS NOT ABANDONED.",
    intro: "One evidenced case, every responsible service, and an independent check of the result.",
    proofLabel: "Public proof",
    proofTitle: "A closed ticket does not mean a clean street",
    proofBody: "The authority closed its ticket. Residents still see the problem. Nahlas keeps both truths separate.",
    casesTitle: "Open cases",
    casesIntro: "Check whether the same case already exists. Corroboration strengthens one case without creating another submission.",
    caseLabel: "Case",
    witnesses: "corroborations",
    days: "days documented",
    authority: "Authority state",
    observed: "Observed on the street",
    timeline: "Evidence chain",
    corroborate: "This is the same problem",
    corroborated: "Corroboration added",
    receipt: "Routing receipt",
    destination: "Destination",
    channel: "Channel",
    sentAt: "Sent",
    externalRef: "External reference",
    payloadHash: "Payload fingerprint",
    simulator: "Demonstration only. Nothing is sent to an authority.",
    hotspot: "Recurring location",
    hotspotBody: "Individual incidents remain separate cases. The dossier shows recurrence and intervention history.",
    howTitle: "Not a complaint box. An outcome loop.",
    step1: "Find or create one case",
    step2: "Get a route and receipt",
    step3: "Recheck the street after the reply",
    reportTitle: "Find a match first",
    reportBody: "Choose a category, district, and public location. The form finds a match and sends nothing outside the browser.",
    category: "Problem type",
    district: "District",
    locationField: "Public location",
    findMatch: "Find similar cases",
    close: "Close",
    demoLabel: "Browser demonstration",
    unresolvedStamp: "Still<br />observed",
    truthNote: "An authority closure does not change the street observation.",
    memberCases: "separate<br />cases",
    matchFound: "A match already exists",
    matchAction: "Corroborate this case",
    noMatch: "No similar public cases found.",
    noDeadline: "No deadline claimed: an ordinary report starts no universal legal clock.",
    status: {
      sent: "Sent",
      accepted: "Accepted by authority",
      closed: "Closed by authority",
      unresolved: "Problem still observed",
      needs_recheck: "Recheck needed",
      fixed: "Fixed and verified"
    }
  }
};

export const seedCases = [
  {
    id: "P8-KAR-014",
    title: {
      ru: "Мусор снова появился у выхода из метро",
      cs: "Odpad se znovu objevil u výstupu z metra",
      en: "Waste returned by the metro exit"
    },
    category: "street-waste",
    categoryLabel: { ru: "Мусор на улице", cs: "Odpad v ulici", en: "Street waste" },
    location: "Křižíkova · Karlín",
    district: "Praha 8",
    createdAt: "2026-08-06T08:20:00.000Z",
    documentedDays: 14,
    authorityState: "closed",
    observedState: "unresolved",
    externalSubmissionCount: 1,
    corroborations: [
      { observerId: "public-a1", at: "2026-08-06T08:20:00.000Z", evidence: "redacted-photo" },
      { observerId: "public-b2", at: "2026-08-08T17:05:00.000Z", evidence: null },
      { observerId: "public-c3", at: "2026-08-15T07:40:00.000Z", evidence: "redacted-photo" }
    ],
    receipts: [
      {
        id: "receipt-p8-014",
        destination: "MČ Praha 8 · odbor životního prostředí",
        channel: "simulated email adapter",
        sentAt: "2026-08-06T09:02:00.000Z",
        state: "accepted",
        payloadHash: "sha256:8b7f…c214",
        externalReference: "P8-DEMO-240806"
      }
    ],
    timeline: [
      { id: "evt-1", type: "reported", at: "2026-08-06T08:20:00.000Z", source: "resident", label: { ru: "Опубликовано первое сообщение", cs: "Zveřejněn první podnět", en: "First report published" } },
      { id: "evt-2", type: "routed", at: "2026-08-06T09:02:00.000Z", source: "router", label: { ru: "Создана квитанция маршрута", cs: "Vytvořen doklad o směrování", en: "Routing receipt created" } },
      { id: "evt-3", type: "authority_closed", at: "2026-08-12T14:18:00.000Z", source: "authority", label: { ru: "Служба закрыла свой тикет", cs: "Úřad uzavřel svůj tiket", en: "Authority closed its ticket" } },
      { id: "evt-4", type: "recheck_failed", at: "2026-08-15T07:40:00.000Z", source: "resident", label: { ru: "Повторная проверка: проблема осталась", cs: "Kontrola: problém trvá", en: "Recheck: problem remains" } }
    ]
  },
  {
    id: "P8-KAR-011",
    title: { ru: "Пакеты и стекло у контейнеров", cs: "Pytle a sklo u kontejnerů", en: "Bags and glass beside the bins" },
    category: "street-waste",
    categoryLabel: { ru: "Мусор на улице", cs: "Odpad v ulici", en: "Street waste" },
    location: "Křižíkova · Karlín",
    district: "Praha 8",
    createdAt: "2026-07-22T18:10:00.000Z",
    documentedDays: 4,
    authorityState: "closed",
    observedState: "fixed",
    externalSubmissionCount: 1,
    corroborations: [{ observerId: "public-d4", at: "2026-07-22T18:10:00.000Z", evidence: "redacted-photo" }],
    receipts: [],
    timeline: []
  },
  {
    id: "P8-KAR-007",
    title: { ru: "Повторный навал картона", cs: "Opakovaná hromada kartonu", en: "Recurring cardboard pile" },
    category: "street-waste",
    categoryLabel: { ru: "Мусор на улице", cs: "Odpad v ulici", en: "Street waste" },
    location: "Křižíkova · Karlín",
    district: "Praha 8",
    createdAt: "2026-07-03T06:40:00.000Z",
    documentedDays: 3,
    authorityState: "closed",
    observedState: "fixed",
    externalSubmissionCount: 1,
    corroborations: [{ observerId: "public-e5", at: "2026-07-03T06:40:00.000Z", evidence: null }],
    receipts: [],
    timeline: []
  }
];

export const reportOptions = {
  categories: [
    { value: "street-waste", label: { ru: "Мусор на улице", cs: "Odpad v ulici", en: "Street waste" } },
    { value: "graffiti", label: { ru: "Граффити", cs: "Graffiti", en: "Graffiti" } },
    { value: "lighting", label: { ru: "Неисправное освещение", cs: "Nefunkční osvětlení", en: "Broken street lighting" } }
  ],
  districts: ["Praha 8", "Praha 3", "Praha 5"]
};
